/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.o3.bitcoin.ui.screens.stores;

import chrriis.dj.nativeswing.swtimpl.components.JWebBrowser;
import chrriis.dj.nativeswing.swtimpl.components.JWebBrowserWindow;
import chrriis.dj.nativeswing.swtimpl.components.WebBrowserAdapter;
import chrriis.dj.nativeswing.swtimpl.components.WebBrowserNavigationEvent;
import chrriis.dj.nativeswing.swtimpl.components.WebBrowserWindowFactory;
import chrriis.dj.nativeswing.swtimpl.components.WebBrowserWindowWillOpenEvent;
import com.o3.bitcoin.model.manager.WalletManager;
import com.o3.bitcoin.service.WalletService;
import com.o3.bitcoin.ui.dialogs.screens.BasicScreen;
import com.o3.bitcoin.applications.PnlShapshiftIOExchangeDividerScreen;
import com.o3.bitcoin.ui.screens.exchange.PnlExchangeScreen;
import com.o3.bitcoin.util.ResourcesProvider.Colors;
import com.o3.bitcoin.util.ResourcesProvider.Fonts;
import java.awt.BorderLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.SwingUtilities;
import org.bitcoinj.uri.BitcoinURI;
import org.bitcoinj.uri.BitcoinURIParseException;

/**
 *
 * @author
 */
/**
 * Class that implements Stores screen of UI 
 */
public class PnlStoresScreen extends javax.swing.JPanel  implements BasicScreen{
    private JTabbedPane tabbedPane;
     private WalletService currentService = null;
    /**
     * Creates new form PnlStoresScreen
     */
    public PnlStoresScreen() {
        initComponents();
        navigateStore();
        currentService = WalletManager.get().getCurentWalletService();
    }

    public void loadData() {
        currentService = WalletManager.get().getCurentWalletService();
        PnlShapshiftIOExchangeDividerScreen.stopMarketInfoTimer();
        PnlExchangeScreen.stopTimers();
    }
    
    /**
     * function that navigates store page
     */
    public void navigateStore() {
        tabbedPane = new JTabbedPane();
        TabbedBrowser webBrowser = new TabbedBrowser("https://o3wallet.com/spend-bitcoin-wallet",tabbedPane,"Stores Home",currentService);
        tabbedPane.addTab("Stores Home", webBrowser);
        add(tabbedPane, BorderLayout.CENTER);
    }
    
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTop = new javax.swing.JPanel();
        pnlTopEdge = new javax.swing.JPanel();
        pnlTitle = new javax.swing.JPanel();
        lblTop = new javax.swing.JLabel();
        pnlBrowser = new javax.swing.JPanel();

        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        pnlTop.setBackground(Colors.SCREEN_TOP_PANEL_BG_COLOR);
        pnlTop.setBorder(new javax.swing.border.MatteBorder(null));
        pnlTop.setMinimumSize(new java.awt.Dimension(86, 38));
        pnlTop.setPreferredSize(new java.awt.Dimension(1024, 50));
        pnlTop.setLayout(new java.awt.BorderLayout());

        pnlTopEdge.setBackground(Colors.NAV_MENU_CONTACTS_COLOR);
        pnlTopEdge.setPreferredSize(new java.awt.Dimension(1024, 5));
        pnlTop.add(pnlTopEdge, java.awt.BorderLayout.NORTH);

        pnlTitle.setBackground(Colors.SCREEN_TOP_PANEL_BG_COLOR);
        pnlTitle.setPreferredSize(new java.awt.Dimension(86, 24));
        pnlTitle.setLayout(new java.awt.GridBagLayout());

        lblTop.setFont(Fonts.BOLD_SMALL_FONT);
        lblTop.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/store_16x16.png"))); // NOI18N
        lblTop.setText("STORES");
        pnlTitle.add(lblTop, new java.awt.GridBagConstraints());

        pnlTop.add(pnlTitle, java.awt.BorderLayout.EAST);

        add(pnlTop, java.awt.BorderLayout.PAGE_START);

        pnlBrowser.setLayout(new java.awt.BorderLayout());
        add(pnlBrowser, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblTop;
    private javax.swing.JPanel pnlBrowser;
    private javax.swing.JPanel pnlTitle;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JPanel pnlTopEdge;
    // End of variables declaration//GEN-END:variables
}
