/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.o3.bitcoin.ui;

import com.o3.bitcoin.util.ResourcesProvider;
import com.o3.bitcoin.util.ResourcesProvider.Colors;
import com.o3.bitcoin.util.ResourcesProvider.Dimensions;
import com.o3.bitcoin.util.ResourcesProvider.Fonts;
import java.awt.Color;
import java.awt.Dimension;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * @author
 */

/**
 * <p> Class that creates title bar of ApplicationUI form</p>
*/
public class PnlTitleBar extends javax.swing.JPanel {

    private static final Logger logger = LoggerFactory.getLogger(PnlTitleBar.class);
    private int x;
    private int y;

    /**
     * Creates new form PnlTitleBar
     */
    public PnlTitleBar() {
        initComponents();
        lblSupport.setText(" ");
        lblSupport.setVisible(true);
        lblUser.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTop = new javax.swing.JPanel();
        pnlControls = new javax.swing.JPanel();
        lblMinimize = new javax.swing.JLabel();
        lblMaximize = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        pnlTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        pnlTopNav = new javax.swing.JPanel();
        lblSupport = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();

        setBackground(Colors.TITLE_BAR_BG_COLOR);
        setLayout(new java.awt.BorderLayout());

        pnlTop.setBackground(Colors.TITLE_BAR_BG_COLOR);
        pnlTop.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlTop.setPreferredSize(new Dimension(1024, Dimensions.TITLE_BAR_HEIGHT));
        pnlTop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlTopMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlTopMousePressed(evt);
            }
        });
        pnlTop.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlTopMouseDragged(evt);
            }
        });
        pnlTop.setLayout(new java.awt.BorderLayout());

        pnlControls.setOpaque(false);
        pnlControls.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        lblMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/minimize.png"))); // NOI18N
        lblMinimize.setToolTipText("Minimize");
        lblMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblMinimizeMousePressed(evt);
            }
        });
        pnlControls.add(lblMinimize);

        lblMaximize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/maximize.png"))); // NOI18N
        lblMaximize.setToolTipText("Restore/Maximize");
        lblMaximize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMaximize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblMaximizeMousePressed(evt);
            }
        });
        pnlControls.add(lblMaximize);

        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/close.png"))); // NOI18N
        lblClose.setToolTipText("Exit");
        lblClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCloseMousePressed(evt);
            }
        });
        pnlControls.add(lblClose);

        pnlTop.add(pnlControls, java.awt.BorderLayout.CENTER);

        pnlTitle.setForeground(Color.WHITE);
        pnlTitle.setOpaque(false);

        lblTitle.setFont(Fonts.BOLD_SMALL_FONT);
        lblTitle.setForeground(Color.BLACK);
        lblTitle.setText(ResourcesProvider.APP_TITLE_VERSION);
        pnlTitle.add(lblTitle);

        pnlTop.add(pnlTitle, java.awt.BorderLayout.WEST);

        add(pnlTop, java.awt.BorderLayout.NORTH);

        pnlTopNav.setBackground(Colors.TITLE_BAR_NAV_BG_COLOR);
        pnlTopNav.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 0, 0));

        lblSupport.setFont(Fonts.BOLD_MEDIUM_FONT);
        lblSupport.setForeground(Colors.TITLE_BAR_NAV_BUTTON_COLOR);
        lblSupport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSupport.setText("Support/Help");
        lblSupport.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblSupport.setPreferredSize(new java.awt.Dimension(110, 45));
        pnlTopNav.add(lblSupport);

        lblUser.setBackground(Colors.TITLE_BAR_NAV_BUTTON_BIG_BG_COLOR);
        lblUser.setFont(Fonts.BOLD_MEDIUM_FONT);
        lblUser.setForeground(Colors.TITLE_BAR_NAV_BUTTON_COLOR);
        lblUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/default_user_dp.png"))); // NOI18N
        lblUser.setText("Username");
        lblUser.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblUser.setIconTextGap(10);
        lblUser.setOpaque(true);
        lblUser.setPreferredSize(new java.awt.Dimension(115, 45));
        pnlTopNav.add(lblUser);

        add(pnlTopNav, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void lblMinimizeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMousePressed
        ApplicationUI.get().minimize();
    }//GEN-LAST:event_lblMinimizeMousePressed

    private void lblMaximizeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMaximizeMousePressed
        ApplicationUI.get().maximize();
    }//GEN-LAST:event_lblMaximizeMousePressed

    private void lblCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMousePressed
        System.exit(0);
    }//GEN-LAST:event_lblCloseMousePressed

    private void pnlTopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTopMouseClicked
        if (evt.getClickCount() >= 2) {
            ApplicationUI.get().maximize();
        }
    }//GEN-LAST:event_pnlTopMouseClicked

    private void pnlTopMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTopMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_pnlTopMousePressed

    private void pnlTopMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTopMouseDragged
        ApplicationUI.get().setLocation(evt.getXOnScreen() - x, evt.getYOnScreen() - y);
    }//GEN-LAST:event_pnlTopMouseDragged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblMaximize;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblSupport;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel pnlControls;
    private javax.swing.JPanel pnlTitle;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JPanel pnlTopNav;
    // End of variables declaration//GEN-END:variables
}
