/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.o3.bitcoin.ui.dialogs;

import com.o3.bitcoin.Application;
import com.o3.bitcoin.exception.ClientRuntimeException;
import com.o3.bitcoin.ui.ApplicationUI;
import com.o3.bitcoin.ui.component.XButtonFactory;
import com.o3.bitcoin.ui.dialogs.screens.PnlEulaScreen;
import com.o3.bitcoin.util.ResourcesProvider;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author
 */

/**
 * <p>Class that implements eula dialog</p>
*/
public class DlgEula extends BasicDialog {

    private PnlEulaScreen pnlEulaScreen;
    private List<JButton> controls = new ArrayList<>();
    public static boolean eulaAccepted = false;
    
    
    /**
     * Creates new form DlgEula
     */
    public DlgEula() {
        super(false);
        setupUI();
    }
    
    @Override
    protected JPanel getMainContentPanel() {
        if (pnlEulaScreen == null) {
            pnlEulaScreen = new PnlEulaScreen();
        }
        return pnlEulaScreen;
    }
    
    @Override
    protected List<JButton> getControls() {
        controls = super.getControls();
        controls.get(0).setText("Decline");
        controls.add(0, getAcceptButton());
        return controls;
    }
    
    /**
     * function to get Accept button for dialog and attach event handler
     * @return Login button
    */
    protected JButton getAcceptButton() {
        JButton acceptButton = new JButton("Accept");
        XButtonFactory.themedButton(acceptButton)
                .background(ResourcesProvider.Colors.NAV_MENU_WALLET_COLOR)
                .color(Color.WHITE)
                .font(ResourcesProvider.Fonts.BOLD_MEDIUM_FONT);
        
        acceptButton.addActionListener(new ActionListener() {
            
            @Override
            public void actionPerformed(ActionEvent e) {
                //check = true;
                handleAcceptButtonClickEvent(e);
            }
        });
        return acceptButton;
    }
    
    /**
     * callback function for Accept button event 
    */
    protected void handleAcceptButtonClickEvent(ActionEvent e) {
        eulaAccepted = true;
        dispose();
    }
    
    @Override
    protected String getHeadingText() {
        return "EULA";
    }
    
    @Override
    protected void handleDefaultCloseEvent(ActionEvent e) {
        handleCloseDialogControlEvent(e);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
