/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.o3.bitcoin.ui.dialogs;

import com.o3.bitcoin.service.WalletService;
import com.o3.bitcoin.ui.ApplicationUI;
import com.o3.bitcoin.ui.component.XButtonFactory;
import com.o3.bitcoin.ui.dialogs.screens.PnlRenameAccountScreen;
import com.o3.bitcoin.util.ResourcesProvider;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JPanel;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * @author
 */

/**
 * <p>Class that implements ui dialog to rename account</p>
*/
public class DlgRenameAccount extends BasicDialog {
    
    private static final Logger logger = LoggerFactory.getLogger(DlgCreateNewAccount.class);
    private WalletService service = null;
    private PnlRenameAccountScreen pnlRenameAccountScreen;
    private List<JButton> controls = new ArrayList<>();
    private String oldAccountName; 
    private String newAccountName;


    /**
     * Creates new form DlgRenameAccount
     *
     * @param service
     */
    public DlgRenameAccount(WalletService service, String oldAccountName) {
        super(false);
        this.service = service;
        this.oldAccountName = oldAccountName;
        setupUI();
    }
    
        @Override
    protected JPanel getMainContentPanel() {
        if (pnlRenameAccountScreen == null) {
            pnlRenameAccountScreen = new PnlRenameAccountScreen(this, service, oldAccountName);
        }
        return pnlRenameAccountScreen;
    }


    @Override
    protected List<JButton> getControls() {
        controls = super.getControls();
        controls.add(0, getRenameAccountButton());
        return controls;
    }

    /**
     * function to get Rename button for dialog and attach event handler
     * @return Rename button
    */
    protected JButton getRenameAccountButton() {
        JButton accountButton = new JButton("Rename Account");
        XButtonFactory.themedButton(accountButton)
                .background(ResourcesProvider.Colors.NAV_MENU_WALLET_COLOR)
                .color(Color.WHITE)
                .font(ResourcesProvider.Fonts.BOLD_MEDIUM_FONT)
                .size(XButtonFactory.NORMAL_BUTTON_DIMENSION);

        accountButton.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                handleRenameAccountButtonClickEvent(e);
            }
        });
        return accountButton;
    }
    
    public void setNewAccountName(String acctName) {
        this.newAccountName = acctName;
    }
    
    public String getNewAccountName() {
        return this.newAccountName;
    }

    /**
     * callback function for Rename button event 
    */
    protected void handleRenameAccountButtonClickEvent(ActionEvent e) {
        try {
            if(pnlRenameAccountScreen.renameAccount())
                handleCloseDialogControlEvent(e);
        } catch (IllegalArgumentException ex) {
            logger.error("Account rename failed: {}", ex.toString(), ex);
            ApplicationUI.get().showError(ex);
        } catch (Exception ex) {
            logger.error("Account rename failed: {}", ex.getMessage(), ex);
            ApplicationUI.get().showError(ex);
        }
    }

    @Override
    protected String getHeadingText() {
        return "Rename Account";
    }

    @Override
    protected void handleCloseDialogControlEvent(ActionEvent e) {
        super.handleCloseDialogControlEvent(e);
    }

    @Override
    protected void handleDefaultCloseEvent(ActionEvent e) {
        handleCloseDialogControlEvent(e);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
