/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.o3.bitcoin.ui.dialogs;

import com.o3.bitcoin.ui.component.XButtonFactory;
import com.o3.bitcoin.ui.dialogs.screens.PnlScanQRCodeScreen;
import com.o3.bitcoin.ui.dialogs.screens.PnlScanWalletSeedScreen;
import com.o3.bitcoin.util.ResourcesProvider;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JPanel;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * @author
 */

/**
 * <p>Class that implements ui dialog to Scan QRCode and extract wallet seed</p>
*/
public class DlgScanWalletSeed extends BasicDialog {

    private static final Logger logger = LoggerFactory.getLogger(DlgScanWalletSeed.class);
    private PnlScanWalletSeedScreen pnlScanWalletSeedScreen;
    private List<JButton> controls = new ArrayList<>();
    private String qrCodeString = null;
    
    /**
     * Creates new form DlgScanWalletSeed
     */
    public DlgScanWalletSeed() {
        super(false);
        setupUI();
    }
    
    @Override
    protected JPanel getMainContentPanel() {
        if (pnlScanWalletSeedScreen == null) {
            pnlScanWalletSeedScreen = new PnlScanWalletSeedScreen(this);
        }
        return pnlScanWalletSeedScreen;
    }


    @Override
    protected List<JButton> getControls() {
        controls = super.getControls();
        return controls;
    }
    
    protected JButton getCloseDialogControl() {
        JButton close = getCloseButton();
        close.addActionListener(new ActionListener() {
            
            @Override
            public void actionPerformed(ActionEvent e) {
                pnlScanWalletSeedScreen.closeCamera();
                handleCloseDialogControlEvent(e);
            }
        });
        return close;
    }
    
    public String getQRCode() {
       return pnlScanWalletSeedScreen.getQRCode();
    }

    @Override
    protected String getHeadingText() {
        return "Scan Wallet Seed";
    }

    @Override
    protected void handleCloseDialogControlEvent(ActionEvent e) {
        pnlScanWalletSeedScreen.closeCamera();
        super.handleCloseDialogControlEvent(e);
    }

    @Override
    protected void handleDefaultCloseEvent(ActionEvent e) {
        handleCloseDialogControlEvent(e);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
