/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.o3.bitcoin.ui.dialogs;

import com.o3.bitcoin.ui.component.XButtonFactory;
import com.o3.bitcoin.ui.dialogs.screens.PnlScanQRCodeScreen;
import com.o3.bitcoin.util.ResourcesProvider;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JPanel;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * @author
 */

/**
 * <p>Class that implements ui dialog to Scan QRCode and extract address</p>
*/
public class DlgScanQRCode extends BasicDialog {
    
    private static final Logger logger = LoggerFactory.getLogger(DlgCreateNewAccount.class);
    private PnlScanQRCodeScreen pnlScanQRCodeScreen;
    private List<JButton> controls = new ArrayList<>();
    private String qrCodeString = null;
    private boolean isPnlNewPaymentScreen=true;

    /**
     * Creates new form DlgScanQRCode
     */
    public DlgScanQRCode() {
        super(false);
        setupUI();
    }
    public DlgScanQRCode(boolean isPnlNewPaymentScreen) {
        super(false);
        this.isPnlNewPaymentScreen=isPnlNewPaymentScreen;
        setupUI();
    }
    
    @Override
    protected JPanel getMainContentPanel() {
        if (pnlScanQRCodeScreen == null) {
            pnlScanQRCodeScreen = new PnlScanQRCodeScreen(this);
            pnlScanQRCodeScreen.setIsPnlNewPaymentScreen(isPnlNewPaymentScreen);
        }
        return pnlScanQRCodeScreen;
    }
    
    @Override
    protected List<JButton> getControls() {
        controls = super.getControls();
        //controls.add(0, getScanQRCodeButton());
        return controls;
    }
    
    @Override
    protected JButton getCloseDialogControl() {
        JButton close = getCloseButton();
        close.addActionListener(new ActionListener() {
            
            @Override
            public void actionPerformed(ActionEvent e) {
                pnlScanQRCodeScreen.closeCamera();
                handleCloseDialogControlEvent(e);
                dispose();            
            }
        });
        return close;
    }
    
    /**
     * function to get Scan button for dialog and attach event handler
     * @return Scan button
    */
    protected JButton getScanQRCodeButton() {
        JButton button = new JButton("Scan");
        XButtonFactory.themedButton(button)
                .background(ResourcesProvider.Colors.NAV_MENU_WALLET_COLOR)
                .color(Color.WHITE)
                .font(ResourcesProvider.Fonts.BOLD_MEDIUM_FONT)
                .size(XButtonFactory.NORMAL_BUTTON_DIMENSION);

        button.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                handleScanQRCodetButtonClickEvent(e);
            }
        });
        return button;
    }

    /**
     * callback function for Scan button event 
    */
    protected void handleScanQRCodetButtonClickEvent(ActionEvent e) {
       pnlScanQRCodeScreen.scanQRCode();
    }
    
    public String getQRCode() {
       return pnlScanQRCodeScreen.getQRCode();
    }

    @Override
    protected String getHeadingText() {
        return "Scan QRCode";
    }

    @Override
    protected void handleCloseDialogControlEvent(ActionEvent e) {
        pnlScanQRCodeScreen.closeCamera();
        super.handleCloseDialogControlEvent(e);
    }

    @Override
    protected void handleDefaultCloseEvent(ActionEvent e) {
        handleCloseDialogControlEvent(e);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
