/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.o3.bitcoin.ui.dialogs;

import com.o3.bitcoin.ui.component.XButtonFactory;
import com.o3.bitcoin.ui.dialogs.screens.PnlQRCodeScreen;
import com.o3.bitcoin.ui.dialogs.screens.PnlWalletSeedQRCodeScreen;
import com.o3.bitcoin.util.ImageSelection;
import com.o3.bitcoin.util.ResourcesProvider;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JPanel;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * @author
 */

/**
 * <p>Class that implements ui dialog to show QRCode of wallet seed</p>
*/
public class DlgWalletSeedQRCode extends BasicDialog {
    
    private static final Logger logger = LoggerFactory.getLogger(DlgWalletSeedQRCode.class);
    private PnlWalletSeedQRCodeScreen pnlWsQrCodeScreen;
    private List<JButton> controls = new ArrayList<>();

    /**
     * Creates new form DlgWalletSeedQRCode
     */
    public DlgWalletSeedQRCode() {
        super(false);
        setupUI();
    }
    
    @Override
    protected JPanel getMainContentPanel() {
        if (pnlWsQrCodeScreen == null) {
            pnlWsQrCodeScreen = new PnlWalletSeedQRCodeScreen();
        }
        return pnlWsQrCodeScreen;
    }


    @Override
    protected List<JButton> getControls() {
        controls = super.getControls();
        controls.add(0, getCopyQRCodeButton());
        return controls;
    }

    /**
     * function to get Copy button for dialog and attach event handler
     * @return Copy button
    */
    protected JButton getCopyQRCodeButton() {
        JButton copyButton = new JButton("Copy");
        XButtonFactory.themedButton(copyButton)
                .background(ResourcesProvider.Colors.NAV_MENU_WALLET_COLOR)
                .color(Color.WHITE)
                .font(ResourcesProvider.Fonts.BOLD_MEDIUM_FONT)
                .size(XButtonFactory.NORMAL_BUTTON_DIMENSION);

        copyButton.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                handleCopyQRCodetButtonClickEvent(e);
            }
        });
        return copyButton;
    }

    /**
     * callback function for Copy button event 
    */
    protected void handleCopyQRCodetButtonClickEvent(ActionEvent e) {
        ImageSelection imgSel = new ImageSelection(new ImageIcon(pnlWsQrCodeScreen.getQrcodeFilePath()).getImage());
        Toolkit.getDefaultToolkit().getSystemClipboard().setContents(imgSel, null);
    }
    
    private void deleteQRCodeFile() {
        File file = new File(pnlWsQrCodeScreen.getQrcodeFilePath());
        if( file.exists() )
            file.delete();
    }

    @Override
    protected String getHeadingText() {
        return "Wallet Seed QRCode";
    }

    @Override
    protected void handleCloseDialogControlEvent(ActionEvent e) {
        super.handleCloseDialogControlEvent(e);
        deleteQRCodeFile();
    }

    @Override
    protected void handleDefaultCloseEvent(ActionEvent e) {
        handleCloseDialogControlEvent(e);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
