/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.o3.bitcoin.ui.dialogs.screens;

/**
 *
 * @author
 */

/**
 * <p>Class that creates UI form for eula dialog</p>
*/
public class PnlEulaScreen extends javax.swing.JPanel {

    /**
     * Creates new form PnlEulaScreen
     */
    public PnlEulaScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEula = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        lblEula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eula.png"))); // NOI18N
        lblEula.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(lblEula, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblEula;
    // End of variables declaration//GEN-END:variables
}
