/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.o3.bitcoin.ui.dialogs.screens;

import com.o3.bitcoin.exception.ClientRuntimeException;
import com.o3.bitcoin.model.manager.ConfigManager;
import com.o3.bitcoin.model.manager.WalletManager;
import com.o3.bitcoin.service.WalletService;
import com.o3.bitcoin.ui.ApplicationUI;
import com.o3.bitcoin.util.ResourcesProvider;
import com.o3.bitcoin.util.Utils;
import org.bitcoinj.crypto.KeyCrypter;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.spongycastle.crypto.params.KeyParameter;

/**
 *
 * @author
 */
public class PnlManageApplicationPasswordScreen extends javax.swing.JPanel {

    private static final Logger logger = LoggerFactory.getLogger(PnlManageApplicationPasswordScreen.class);
    private KeyParameter key;

    /**
     * Creates new form PnlNewPaymentScreen
     *
     * @param service
     */
    public PnlManageApplicationPasswordScreen() {
        initComponents();
    }

    public void validateData() throws IllegalArgumentException,ClientRuntimeException{
        String oldPass = txtOldPassword.getPassword() != null ? new String(txtOldPassword.getPassword()) : "";
        String newPass = txtNewPassword.getPassword() != null ? new String(txtNewPassword.getPassword()) : "";
        String confirmPass = txtConfirmPassword.getPassword() != null ? new String(txtConfirmPassword.getPassword()) : "";
        if (oldPass.isEmpty()) {
            txtOldPassword.requestFocusInWindow();
            throw new IllegalArgumentException("Old Password is required.");
        }
        if (newPass.isEmpty()) {
            txtNewPassword.requestFocusInWindow();
            throw new IllegalArgumentException("New Password is required.");
        }
        if (newPass.length() < 5 ) {
            txtNewPassword.requestFocusInWindow();
            throw new IllegalArgumentException("Password must be at least 5 characters long");
        }
        if (confirmPass.isEmpty() || !confirmPass.equalsIgnoreCase(newPass)) {
            txtConfirmPassword.requestFocusInWindow();
            throw new IllegalArgumentException("Passwords do not match.");
        }
        if ((confirmPass.length() < 5)) {
            txtConfirmPassword.requestFocusInWindow();
            throw new IllegalArgumentException("Password must be at least 5 characters long");
        }
        if( newPass.equals(oldPass)) {
            throw new ClientRuntimeException("Old Passowrd and New Password are same.");
        }
        if( !WalletManager.walletPassword.equals(oldPass)) {
            throw new ClientRuntimeException("Incorrect Old Application Password.");
        }
    }

    public boolean changePassword() {
        try {
            validateData();
            _changePassphrase();
            return true;
        } catch (Exception e) {
            logger.error("Change Password Error: {}", e.getMessage());
            ApplicationUI.get().showError(e.getMessage());
        }
        return false;
    }
    
    
    private void _changePassphrase() throws Exception {
        try{
            String oldPassword = new String(txtOldPassword.getPassword());
            String password = new String(txtNewPassword.getPassword());
            WalletService service = WalletManager.get().getCurentWalletService();
            service.changeAllWalletsPassword(oldPassword,password);
        }catch( Exception e){
            logger.error("Change Password Error: {}", e.getMessage());
            throw e;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblOldPassword = new javax.swing.JLabel();
        txtOldPassword = new javax.swing.JPasswordField();
        lblNewPassword = new javax.swing.JLabel();
        txtNewPassword = new javax.swing.JPasswordField();
        lblConfirmPassword = new javax.swing.JLabel();
        txtConfirmPassword = new javax.swing.JPasswordField();

        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        lblOldPassword.setFont(ResourcesProvider.Fonts.BOLD_MEDIUM_FONT);
        lblOldPassword.setForeground(ResourcesProvider.Colors.DEFAULT_HEADING_COLOR);
        lblOldPassword.setText("Old Password:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblOldPassword, gridBagConstraints);

        txtOldPassword.setFont(ResourcesProvider.Fonts.BOLD_MEDIUM_FONT);
        txtOldPassword.setPreferredSize(new java.awt.Dimension(275, 31));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(txtOldPassword, gridBagConstraints);

        lblNewPassword.setFont(ResourcesProvider.Fonts.BOLD_MEDIUM_FONT);
        lblNewPassword.setForeground(ResourcesProvider.Colors.DEFAULT_HEADING_COLOR);
        lblNewPassword.setText("New Password:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblNewPassword, gridBagConstraints);

        txtNewPassword.setFont(ResourcesProvider.Fonts.BOLD_MEDIUM_FONT);
        txtNewPassword.setPreferredSize(new java.awt.Dimension(275, 33));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(txtNewPassword, gridBagConstraints);

        lblConfirmPassword.setFont(ResourcesProvider.Fonts.BOLD_MEDIUM_FONT);
        lblConfirmPassword.setForeground(ResourcesProvider.Colors.DEFAULT_HEADING_COLOR);
        lblConfirmPassword.setText("Confirm Password:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblConfirmPassword, gridBagConstraints);

        txtConfirmPassword.setFont(ResourcesProvider.Fonts.BOLD_MEDIUM_FONT);
        txtConfirmPassword.setPreferredSize(new java.awt.Dimension(275, 33));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(txtConfirmPassword, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblConfirmPassword;
    private javax.swing.JLabel lblNewPassword;
    private javax.swing.JLabel lblOldPassword;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JPasswordField txtNewPassword;
    private javax.swing.JPasswordField txtOldPassword;
    // End of variables declaration//GEN-END:variables
}
