/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.o3.bitcoin.ui.component.nav;

import com.o3.bitcoin.model.Config;
import com.o3.bitcoin.model.manager.ConfigManager;
import com.o3.bitcoin.ui.ApplicationUI;
import com.o3.bitcoin.ui.DirectionRatio;
import com.o3.bitcoin.ui.ScaleDescriptor;
import com.o3.bitcoin.ui.dialogs.YesNoDialog;
import com.o3.bitcoin.util.ResourcesProvider.Colors;
import com.o3.bitcoin.util.ResourcesProvider.Dimensions;
import com.o3.bitcoin.util.Utils;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author
 */

/**
 * <p>Class that creates left navigation menu ui </p>
*/
public class PnlLeftNavigationMenu extends javax.swing.JPanel {

    /**
     * Creates new form PnlNavigationMenu
     */
    public PnlLeftNavigationMenu() {
        initComponents();
        mnuItemExchange.setVisible(true);
        pnlLeftNavMenuItem3.setVisible(false);
        //mnuItemStores.setVisible(false);
    }
    
    @Override
    public Dimension getMinimumSize() {
        return new Dimension(Dimensions.BASE_NAV_MENU_WIDTH, Dimensions.BASE_NAV_MENU_HEIGHT);
    }
    
    @Override
    public Dimension getPreferredSize() {
        Dimension min = getMinimumSize();
        ScaleDescriptor sd = Utils.createScaleDescriptor(this);
        int width = min.width;
        int height = min.height;
        double directionRatio = sd != null ? sd.getValueByRatio(DirectionRatio.MIN_DIRECTION_RATIO) : 1.0;
        int preferredWidth = (int) ((double) width * directionRatio);
        int preferredHeight = (int) ((double) height * directionRatio);
        return new Dimension(preferredWidth, preferredHeight);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        mnuItemDashboard = new com.o3.bitcoin.ui.component.nav.PnlLeftNavMenuItem("DASHBOARD", "o3", Colors.NAV_MENU_DASHBOARD_COLOR);
        mnuItemWallet = new com.o3.bitcoin.ui.component.nav.PnlLeftNavMenuItem("ACCOUNT", "wallet", Colors.NAV_MENU_WALLET_COLOR);
        pnlLeftNavMenuItem3 = new com.o3.bitcoin.ui.component.nav.PnlLeftNavMenuItem("CONTACTS", "contacts", Colors.NAV_MENU_CONTACTS_COLOR);
        mnuItemExchange = new com.o3.bitcoin.ui.component.nav.PnlLeftNavMenuItem("EXCHANGE", "exchange", Colors.NAV_MENU_EXCHANGE_COLOR);
        mnuItemStores = new com.o3.bitcoin.ui.component.nav.PnlLeftNavMenuItem("STORES", "store", Colors.NAV_MENU_CONTACTS_COLOR);
        pnlLeftNavMenuItem5 = new com.o3.bitcoin.ui.component.nav.PnlLeftNavMenuItem("SETTINGS", "settings", Colors.NAV_MENU_SETTINGS_COLOR);
        pnlLeftNavMenuItem6 = new com.o3.bitcoin.ui.component.nav.PnlLeftNavMenuItem("ABOUT", "info", Colors.NAV_MENU_ABOUT_COLOR);
        pnlSpacer = new javax.swing.JPanel();

        setBackground(Colors.NAV_MENU_BG_COLOR);
        setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, Colors.NAV_MENU_RIGHT_BORDER_COLOR));
        setLayout(new java.awt.BorderLayout());

        pnlMain.setOpaque(false);
        pnlMain.setLayout(new javax.swing.BoxLayout(pnlMain, javax.swing.BoxLayout.PAGE_AXIS));

        mnuItemDashboard.setCaption("DASHBOARD");
        mnuItemDashboard.setEdgeColor(Colors.NAV_MENU_DASHBOARD_COLOR);
        mnuItemDashboard.setIconKey("o3");
        mnuItemDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mnuItemDashboardMousePressed(evt);
            }
        });
        pnlMain.add(mnuItemDashboard);

        mnuItemWallet.setCaption("ACCOUNT");
        mnuItemWallet.setEdgeColor(Colors.NAV_MENU_WALLET_COLOR);
        mnuItemWallet.setIconKey("wallet");
        mnuItemWallet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mnuItemWalletMousePressed(evt);
            }
        });
        pnlMain.add(mnuItemWallet);

        pnlLeftNavMenuItem3.setCaption("CONTACTS");
        pnlLeftNavMenuItem3.setEdgeColor(Colors.NAV_MENU_CONTACTS_COLOR);
        pnlLeftNavMenuItem3.setIconKey("contacts");
        pnlLeftNavMenuItem3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlLeftNavMenuItem3MouseClicked(evt);
            }
        });
        pnlMain.add(pnlLeftNavMenuItem3);

        mnuItemExchange.setCaption("EXCHANGE");
        mnuItemExchange.setEdgeColor(Colors.NAV_MENU_EXCHANGE_COLOR);
        mnuItemExchange.setIconKey("exchange");
        mnuItemExchange.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuItemExchangeMouseClicked(evt);
            }
        });
        pnlMain.add(mnuItemExchange);

        mnuItemStores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuItemStoresMouseClicked(evt);
            }
        });
        pnlMain.add(mnuItemStores);

        pnlLeftNavMenuItem5.setCaption("SETTINGS");
        pnlLeftNavMenuItem5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlLeftNavMenuItem5MousePressed(evt);
            }
        });
        pnlMain.add(pnlLeftNavMenuItem5);

        pnlLeftNavMenuItem6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlLeftNavMenuItem6MouseClicked(evt);
            }
        });
        pnlMain.add(pnlLeftNavMenuItem6);

        add(pnlMain, java.awt.BorderLayout.NORTH);

        pnlSpacer.setOpaque(false);
        pnlSpacer.setLayout(new java.awt.BorderLayout());
        add(pnlSpacer, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuItemDashboardMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuItemDashboardMousePressed
        ApplicationUI.get().showScreen(ApplicationUI.SCREEN_DASHBOARD);
    }//GEN-LAST:event_mnuItemDashboardMousePressed

    private void mnuItemWalletMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuItemWalletMousePressed
        ApplicationUI.get().showScreen(ApplicationUI.SCREEN_WALLET);
    }//GEN-LAST:event_mnuItemWalletMousePressed

    private void pnlLeftNavMenuItem5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLeftNavMenuItem5MousePressed
        ApplicationUI.get().showScreen(ApplicationUI.SCREEN_SETTINGS);
    }//GEN-LAST:event_pnlLeftNavMenuItem5MousePressed

    private void pnlLeftNavMenuItem3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLeftNavMenuItem3MouseClicked
        // TODO add your handling code here:
        YesNoDialog dialog = new YesNoDialog("Info","Contacts is still under Development", false);
        dialog.start();
    }//GEN-LAST:event_pnlLeftNavMenuItem3MouseClicked

    private void pnlLeftNavMenuItem6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLeftNavMenuItem6MouseClicked
        // TODO add your handling code here:
        ApplicationUI.get().showScreen(ApplicationUI.SCREEN_ABOUT);
    }//GEN-LAST:event_pnlLeftNavMenuItem6MouseClicked

    private void mnuItemStoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuItemStoresMouseClicked
        // TODO add your handling code here:
        ApplicationUI.get().showScreen(ApplicationUI.SCREEN_STORES);
    }//GEN-LAST:event_mnuItemStoresMouseClicked

    private void mnuItemExchangeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuItemExchangeMouseClicked
        // TODO add our handling code here:
        Config config = ConfigManager.config();
        String currentNetwork = config.getDefaultNetwork();
        if( currentNetwork.equals("MAINNET")) {
            ApplicationUI.get().showScreen(ApplicationUI.SCREEN_EXCHANGE);
        }
        else
        {
            YesNoDialog dialog = new YesNoDialog("Bitcoin Network Error","Exchange works on Main Net, please change bitcoin network from SETTINGS page", false);
            dialog.start();
        }    
    }//GEN-LAST:event_mnuItemExchangeMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.o3.bitcoin.ui.component.nav.PnlLeftNavMenuItem mnuItemDashboard;
    private com.o3.bitcoin.ui.component.nav.PnlLeftNavMenuItem mnuItemExchange;
    private com.o3.bitcoin.ui.component.nav.PnlLeftNavMenuItem mnuItemStores;
    private com.o3.bitcoin.ui.component.nav.PnlLeftNavMenuItem mnuItemWallet;
    private com.o3.bitcoin.ui.component.nav.PnlLeftNavMenuItem pnlLeftNavMenuItem3;
    private com.o3.bitcoin.ui.component.nav.PnlLeftNavMenuItem pnlLeftNavMenuItem5;
    private com.o3.bitcoin.ui.component.nav.PnlLeftNavMenuItem pnlLeftNavMenuItem6;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlSpacer;
    // End of variables declaration//GEN-END:variables
}
