/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.o3.bitcoin.ui.component.nav;

import com.o3.bitcoin.ui.component.XScalableLabel;
import com.o3.bitcoin.util.ResourcesProvider.Colors;
import com.o3.bitcoin.util.ResourcesProvider.Dimensions;
import com.o3.bitcoin.util.ResourcesProvider.Fonts;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JLabel;

/**
 *
 * @author
 */

/**
 * <p>Class that creates menu item in left navigation menu ui </p>
*/
public class PnlLeftNavMenuItem extends javax.swing.JPanel {

    private String caption;
    private String iconKey;
    private Color edgeColor;

    public PnlLeftNavMenuItem() {
        initComponents();
    }

    /**
     * Creates new form PnlLeftNavMenuItem
     *
     * @param caption
     * @param iconKey
     * @param edgeColor
     */
    public PnlLeftNavMenuItem(String caption, String iconKey, Color edgeColor) {
        this.caption = caption;
        this.iconKey = iconKey;
        this.edgeColor = edgeColor;
        initComponents();
    }

    public String getCaption() {
        return caption;
    }

    public void setCaption(String caption) {
        this.caption = caption;
    }

    public String getIconKey() {
        return iconKey;
    }

    public void setIconKey(String iconKey) {
        this.iconKey = iconKey;
    }

    public Color getEdgeColor() {
        return edgeColor;
    }

    public void setEdgeColor(Color edgeColor) {
        this.edgeColor = edgeColor;
    }
    
    public void setIconBackground(Color iconBackground) {
        lblIcon.setBackground(iconBackground);
    }

    @Override
    public Dimension getMinimumSize() {
        return new Dimension(Dimensions.BASE_NAV_MENU_ITEM_WIDTH, Dimensions.BASE_NAV_MENU_ITEM_HEIGHT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCaption = new XScalableLabel(caption, null, 0);
        pnlIcon = new javax.swing.JPanel();
        lblIcon = new XScalableLabel(null, iconKey, 16, JLabel.CENTER);
        pnlEdge = new javax.swing.JPanel();

        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        lblCaption.setFont(Fonts.NAV_MENU_ITEM_FONT);
        lblCaption.setForeground(Colors.DEFAULT_HEADING_COLOR);
        lblCaption.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, Colors.NAV_MENU_ITEM_BORDER_COLOR), javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0)));
        add(lblCaption, java.awt.BorderLayout.CENTER);

        pnlIcon.setOpaque(false);
        pnlIcon.setPreferredSize(new java.awt.Dimension(50, 50));
        pnlIcon.setLayout(new java.awt.BorderLayout());

        lblIcon.setBackground(Colors.NAV_MENU_BG_COLOR);
        lblIcon.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, Colors.NAV_MENU_ITEM_BORDER_COLOR));
        lblIcon.setOpaque(true);
        pnlIcon.add(lblIcon, java.awt.BorderLayout.CENTER);

        pnlEdge.setBackground(edgeColor);
        pnlEdge.setPreferredSize(new java.awt.Dimension(5, 600));
        pnlIcon.add(pnlEdge, java.awt.BorderLayout.WEST);

        add(pnlIcon, java.awt.BorderLayout.WEST);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCaption;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JPanel pnlEdge;
    private javax.swing.JPanel pnlIcon;
    // End of variables declaration//GEN-END:variables
}
