/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.o3.bitcoin.ui.screens.dashboard;

import com.o3.bitcoin.util.ResourcesProvider.Colors;
import com.o3.bitcoin.util.ResourcesProvider.Fonts;

/**
 *
 * @author
 */

/**
 * Class that shows debit/credit/balance and price in fiat on dashboard screen 
 */
public class PnlDashboardStats extends javax.swing.JPanel {

    /**
     * Creates new form PnlDashboardStats
     */
    public PnlDashboardStats() {
        initComponents();
    }

    /*public void setTotalDebit(String totalDebit) {
        if( totalDebit.contains("-"))
            lblTotalDebit.setText(totalDebit.substring(1));
        else
            lblTotalDebit.setText(totalDebit);
    }*/

    /*public void setTotalCredit(String totalCredit) {
        lblTotalCredit.setText(totalCredit);
    }*/

    public void setTotalBalance(String totalBalance) {
        lblTotalBalance.setText("BTC   -   "+totalBalance);
    }

    public void setPriceInFiat(String priceInFiat, String prefixSymbol, String currencySymbol) {
        lblPriceInFiat.setText(currencySymbol + "   -   "+  priceInFiat);
    }
    
    public void setExchangeRate(String currencySymbol, String exchangeRate) {
        lblConversionRate.setText(currencySymbol+"/BTC   -   "+exchangeRate);
    }

    public void reset() {
        //setTotalDebit("0.0000");
        //setTotalCredit("0.0000");
        setTotalBalance("0.0000");
        setPriceInFiat("0.0000", "", "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlControls = new javax.swing.JPanel();
        pnlBalance = new javax.swing.JPanel();
        pnlContents2 = new javax.swing.JPanel();
        lblTotalBalance = new com.o3.bitcoin.ui.component.XScalableLabel();
        lblPriceInFiat = new com.o3.bitcoin.ui.component.XScalableLabel();
        lblTitle2 = new com.o3.bitcoin.ui.component.XScalableLabel();
        pnlSpacer = new javax.swing.JPanel();
        xScalableLabel1 = new com.o3.bitcoin.ui.component.XScalableLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pnlExchangeRate = new javax.swing.JPanel();
        pnlContents3 = new javax.swing.JPanel();
        lblConversionRate = new com.o3.bitcoin.ui.component.XScalableLabel();
        lblTitle3 = new com.o3.bitcoin.ui.component.XScalableLabel();

        setOpaque(false);

        pnlControls.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(225, 95, 104), 2, true));
        pnlControls.setOpaque(false);
        pnlControls.setLayout(new java.awt.GridLayout(1, 0));

        pnlBalance.setOpaque(false);
        pnlBalance.setLayout(new java.awt.BorderLayout());

        pnlContents2.setOpaque(false);
        pnlContents2.setLayout(new java.awt.GridBagLayout());

        lblTotalBalance.setText("0.0000");
        lblTotalBalance.setFont(Fonts.DEFAULT_HEADING_FONT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        pnlContents2.add(lblTotalBalance, gridBagConstraints);

        lblPriceInFiat.setText("0.0000");
        lblPriceInFiat.setFont(Fonts.DEFAULT_HEADING_FONT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 10, 5, 10);
        pnlContents2.add(lblPriceInFiat, gridBagConstraints);

        pnlBalance.add(pnlContents2, java.awt.BorderLayout.CENTER);

        lblTitle2.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 1, 5, 1));
        lblTitle2.setForeground(Colors.DEFAULT_HEADING_COLOR1);
        lblTitle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle2.setText("Available Balance");
        lblTitle2.setFont(Fonts.DEFAULT_HEADING_FONT);
        pnlBalance.add(lblTitle2, java.awt.BorderLayout.PAGE_START);

        pnlControls.add(pnlBalance);

        pnlSpacer.setOpaque(false);
        pnlSpacer.setLayout(new java.awt.BorderLayout());

        xScalableLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 1, 5, 1));
        xScalableLabel1.setText("  ");
        pnlSpacer.add(xScalableLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setPreferredSize(new java.awt.Dimension(2, 10));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        jPanel1.add(jPanel2, gridBagConstraints);

        pnlSpacer.add(jPanel1, java.awt.BorderLayout.CENTER);

        pnlControls.add(pnlSpacer);

        pnlExchangeRate.setOpaque(false);
        pnlExchangeRate.setLayout(new java.awt.BorderLayout());

        pnlContents3.setOpaque(false);
        pnlContents3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        lblConversionRate.setText("0.0000");
        lblConversionRate.setFont(Fonts.DEFAULT_HEADING_FONT);
        pnlContents3.add(lblConversionRate);

        pnlExchangeRate.add(pnlContents3, java.awt.BorderLayout.CENTER);

        lblTitle3.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 1, 5, 1));
        lblTitle3.setForeground(Colors.DEFAULT_HEADING_COLOR1);
        lblTitle3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle3.setText("Exchange Rate");
        lblTitle3.setFont(Fonts.DEFAULT_HEADING_FONT);
        pnlExchangeRate.add(lblTitle3, java.awt.BorderLayout.PAGE_START);

        pnlControls.add(pnlExchangeRate);

        add(pnlControls);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private com.o3.bitcoin.ui.component.XScalableLabel lblConversionRate;
    private com.o3.bitcoin.ui.component.XScalableLabel lblPriceInFiat;
    private com.o3.bitcoin.ui.component.XScalableLabel lblTitle2;
    private com.o3.bitcoin.ui.component.XScalableLabel lblTitle3;
    private com.o3.bitcoin.ui.component.XScalableLabel lblTotalBalance;
    private javax.swing.JPanel pnlBalance;
    private javax.swing.JPanel pnlContents2;
    private javax.swing.JPanel pnlContents3;
    private javax.swing.JPanel pnlControls;
    private javax.swing.JPanel pnlExchangeRate;
    private javax.swing.JPanel pnlSpacer;
    private com.o3.bitcoin.ui.component.XScalableLabel xScalableLabel1;
    // End of variables declaration//GEN-END:variables
}
