/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.o3.bitcoin.ui.screens.about;

import com.o3.bitcoin.ui.dialogs.screens.BasicScreen;

/**
 *
 * @author
 */
public class PnlAboutScreen extends javax.swing.JPanel implements BasicScreen {

    /**
     * Creates new form PnlAboutScreen
     */
    public PnlAboutScreen() {
        initComponents();
    }
    
    public void loadData() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLicense = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        lblLicense.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLicense.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/about.png"))); // NOI18N
        add(lblLicense, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblLicense;
    // End of variables declaration//GEN-END:variables
}
