/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.o3.bitcoin.ui.screens.wallet;

import com.o3.bitcoin.util.ResourcesProvider.Colors;
import com.o3.bitcoin.util.ResourcesProvider.Fonts;
import java.awt.Color;

/**
 * Class that shows Debit/Credit/Balance stats on Accounts page 
 */
public class PnlWalletStats extends javax.swing.JPanel {

    /**
     * Creates new form PnlDashboardStats
     */
    public PnlWalletStats() {
        initComponents();
    }
    
    public void setDebitAmount(String debit) {
        if( debit.contains("-"))
            lblDebitValue.setText(debit.substring(1));
        else
            lblDebitValue.setText(debit);
    }
    
    public void setCreditAmount(String credit) {
        lblCreditValue.setText(credit);
    }
    
    public void setBalanceAmount(String amount) {
        lblBalanceValue.setText(amount);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDebitFiat = new javax.swing.JPanel();
        lblTitle = new com.o3.bitcoin.ui.component.XScalableLabel();
        pnlContensMain = new javax.swing.JPanel();
        pnlContents = new javax.swing.JPanel();
        lblDebitValue = new com.o3.bitcoin.ui.component.XScalableLabel();
        lblIcon = new com.o3.bitcoin.ui.component.XScalableLabel();
        pnlCreditFiat = new javax.swing.JPanel();
        lblTitle1 = new com.o3.bitcoin.ui.component.XScalableLabel();
        pnlContensMain1 = new javax.swing.JPanel();
        pnlContents1 = new javax.swing.JPanel();
        lblCreditValue = new com.o3.bitcoin.ui.component.XScalableLabel();
        lblIcon1 = new com.o3.bitcoin.ui.component.XScalableLabel();
        pnlBalanceFiat = new javax.swing.JPanel();
        lblTitle2 = new com.o3.bitcoin.ui.component.XScalableLabel();
        pnlContensMain2 = new javax.swing.JPanel();
        pnlContents2 = new javax.swing.JPanel();
        lblBalanceValue = new com.o3.bitcoin.ui.component.XScalableLabel();
        lblIcon2 = new com.o3.bitcoin.ui.component.XScalableLabel();

        setOpaque(false);
        setLayout(new java.awt.GridLayout(1, 0));

        pnlDebitFiat.setOpaque(false);
        pnlDebitFiat.setLayout(new java.awt.BorderLayout());

        lblTitle.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 30, 1));
        lblTitle.setForeground(Colors.DEFAULT_HEADING_COLOR);
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Debit");
        lblTitle.setFont(Fonts.DEFAULT_HEADING_FONT);
        pnlDebitFiat.add(lblTitle, java.awt.BorderLayout.PAGE_START);

        pnlContensMain.setOpaque(false);
        pnlContensMain.setLayout(new java.awt.BorderLayout());

        pnlContents.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 1, 1));
        pnlContents.setOpaque(false);

        lblDebitValue.setForeground(Color.BLACK);
        lblDebitValue.setText("0");
        lblDebitValue.setFont(Fonts.WALLETS_STATISTICS_FONT);
        pnlContents.add(lblDebitValue);

        pnlContensMain.add(pnlContents, java.awt.BorderLayout.CENTER);

        lblIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bitcoin-debit-32X32.png"))); // NOI18N
        pnlContensMain.add(lblIcon, java.awt.BorderLayout.PAGE_START);

        pnlDebitFiat.add(pnlContensMain, java.awt.BorderLayout.CENTER);

        add(pnlDebitFiat);

        pnlCreditFiat.setOpaque(false);
        pnlCreditFiat.setLayout(new java.awt.BorderLayout());

        lblTitle1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 30, 1));
        lblTitle1.setForeground(Colors.DEFAULT_HEADING_COLOR);
        lblTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle1.setText("Credit");
        lblTitle1.setFont(Fonts.DEFAULT_HEADING_FONT
        );
        pnlCreditFiat.add(lblTitle1, java.awt.BorderLayout.PAGE_START);

        pnlContensMain1.setOpaque(false);
        pnlContensMain1.setLayout(new java.awt.BorderLayout());

        pnlContents1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 1, 1));
        pnlContents1.setOpaque(false);

        lblCreditValue.setForeground(Color.BLACK);
        lblCreditValue.setText("0");
        lblCreditValue.setFont(Fonts.WALLETS_STATISTICS_FONT);
        pnlContents1.add(lblCreditValue);

        pnlContensMain1.add(pnlContents1, java.awt.BorderLayout.CENTER);

        lblIcon1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bitcoin-credit32X32.png"))); // NOI18N
        pnlContensMain1.add(lblIcon1, java.awt.BorderLayout.PAGE_START);

        pnlCreditFiat.add(pnlContensMain1, java.awt.BorderLayout.CENTER);

        add(pnlCreditFiat);

        pnlBalanceFiat.setOpaque(false);
        pnlBalanceFiat.setLayout(new java.awt.BorderLayout());

        lblTitle2.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 30, 1));
        lblTitle2.setForeground(Colors.DEFAULT_HEADING_COLOR);
        lblTitle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle2.setText("Balance");
        lblTitle2.setFont(Fonts.DEFAULT_HEADING_FONT
        );
        pnlBalanceFiat.add(lblTitle2, java.awt.BorderLayout.PAGE_START);

        pnlContensMain2.setOpaque(false);
        pnlContensMain2.setLayout(new java.awt.BorderLayout());

        pnlContents2.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 1, 1));
        pnlContents2.setOpaque(false);

        lblBalanceValue.setForeground(Color.BLACK);
        lblBalanceValue.setText("0");
        lblBalanceValue.setFont(Fonts.WALLETS_STATISTICS_FONT);
        pnlContents2.add(lblBalanceValue);

        pnlContensMain2.add(pnlContents2, java.awt.BorderLayout.CENTER);

        lblIcon2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bitcoin-balance-32X32.png"))); // NOI18N
        pnlContensMain2.add(lblIcon2, java.awt.BorderLayout.PAGE_START);

        pnlBalanceFiat.add(pnlContensMain2, java.awt.BorderLayout.CENTER);

        add(pnlBalanceFiat);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.o3.bitcoin.ui.component.XScalableLabel lblBalanceValue;
    private com.o3.bitcoin.ui.component.XScalableLabel lblCreditValue;
    private com.o3.bitcoin.ui.component.XScalableLabel lblDebitValue;
    private com.o3.bitcoin.ui.component.XScalableLabel lblIcon;
    private com.o3.bitcoin.ui.component.XScalableLabel lblIcon1;
    private com.o3.bitcoin.ui.component.XScalableLabel lblIcon2;
    private com.o3.bitcoin.ui.component.XScalableLabel lblTitle;
    private com.o3.bitcoin.ui.component.XScalableLabel lblTitle1;
    private com.o3.bitcoin.ui.component.XScalableLabel lblTitle2;
    private javax.swing.JPanel pnlBalanceFiat;
    private javax.swing.JPanel pnlContensMain;
    private javax.swing.JPanel pnlContensMain1;
    private javax.swing.JPanel pnlContensMain2;
    private javax.swing.JPanel pnlContents;
    private javax.swing.JPanel pnlContents1;
    private javax.swing.JPanel pnlContents2;
    private javax.swing.JPanel pnlCreditFiat;
    private javax.swing.JPanel pnlDebitFiat;
    // End of variables declaration//GEN-END:variables
}
